/**
 * Mirrors backend ActivityActions / EntityTypes for filter dropdowns.
 * Keep in sync with uat.dharwin.backend/src/config/activityLog.js
 */
export const ACTIVITY_LOG_ACTIONS: string[] = [
  "role.create",
  "role.update",
  "role.delete",
  "user.create",
  "user.update",
  "user.delete",
  "user.disable",
  "impersonation.start",
  "impersonation.end",
  "category.create",
  "category.update",
  "category.delete",
  "student.update",
  "student.delete",
  "mentor.update",
  "mentor.delete",
  "student.course.start",
  "student.course.complete",
  "student.quiz.attempt",
  "certificate.issued",
  "attendance.punchIn",
  "attendance.punchOut",
  "attendance.punchOutByAdmin",
  "attendance.autoPunchOut",
  "candidate.create",
  "candidate.update",
  "candidate.delete",
  "job.create",
  "job.update",
  "job.delete",
  "jobApplication.create",
  "jobApplication.update",
  "jobApplication.delete",
  "settings.bolnaCandidateAgent.update",
];

export const ACTIVITY_LOG_ENTITY_TYPES: string[] = [
  "Role",
  "User",
  "Impersonation",
  "Category",
  "Student",
  "Mentor",
  "StudentCourseProgress",
  "StudentQuizAttempt",
  "Certificate",
  "Attendance",
  "Candidate",
  "Job",
  "JobApplication",
  "BolnaCandidateAgentSettings",
];
