import type { NotificationType } from "@/shared/lib/api/notifications";

export const notifTypeToIcon: Record<NotificationType | string, string> = {
  leave: "clock",
  task: "circle-check",
  offer: "gift",
  meeting: "video",
  meeting_reminder: "video",
  course: "book",
  certificate: "certificate",
  job_application: "briefcase",
  project: "folder",
  account: "user-check",
  recruiter: "user",
  assignment: "user-plus",
  sop: "checklist",
  support_ticket: "lifebuoy",
  chat_message: "message-circle",
  joining_reminder: "calendar-event",
  placement_update: "trophy",
  onboarding_reminder: "user-plus",
  system: "settings",
  general: "bell",
};

export const notifTypeToColor: Record<NotificationType | string, string> = {
  leave: "primary",
  task: "success",
  offer: "secondary",
  meeting: "primary",
  meeting_reminder: "primary",
  course: "pinkmain",
  certificate: "warning",
  job_application: "secondary",
  project: "primary",
  account: "success",
  recruiter: "pinkmain",
  assignment: "primary",
  sop: "primary",
  support_ticket: "warning",
  chat_message: "primary",
  joining_reminder: "success",
  placement_update: "success",
  onboarding_reminder: "primary",
  system: "secondary",
  general: "secondary",
};
