import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import { AiNudgeBadge } from "@/shared/components/AiNudgeBadge";

describe("AiNudgeBadge", () => {
  it("labels the nudge as generated by AI", () => {
    render(<AiNudgeBadge />);
    expect(screen.getByLabelText("Generated by AI")).toHaveTextContent("AI");
  });
});
