"use client";

/**
 * Compact “AI” pill so smart nudges are visually distinct from transactional alerts.
 * @param props.size `sm` for bell/toasts, `md` for the notifications feed
 */
export function AiNudgeBadge({ size = "sm" }: { size?: "sm" | "md" }) {
  const compact = size === "sm";
  return (
    <span
      className={`shrink-0 inline-flex items-center gap-0.5 rounded-full font-semibold uppercase tracking-wide text-fuchsia-700 bg-fuchsia-100 ring-1 ring-fuchsia-200/80 dark:text-fuchsia-300 dark:bg-fuchsia-900/40 dark:ring-fuchsia-700/50 ${
        compact ? "px-1.5 py-px text-[0.6rem]" : "px-2 py-0.5 text-[0.6875rem]"
      }`}
      title="Generated by AI"
      aria-label="Generated by AI"
    >
      <i className={`ri-sparkling-2-fill ${compact ? "text-[0.65rem]" : "text-[0.75rem]"}`} aria-hidden />
      AI
    </span>
  );
}
